"use client";

import React from 'react';
import Header from '@/components/Header';
import { Button } from "@/components/ui/button";

const SuccessStoriesAIRehabilitation = () => {
  return (
    <div className="min-h-screen flex flex-col bg-white dark:bg-gray-950">
      <Header />

      <main className="flex-1">
        {/* Hero Section */}
        <section className="relative py-16 bg-gradient-to-b from-blue-50 to-white dark:from-blue-950 dark:to-gray-950">
          <div className="container mx-auto px-6 max-w-3xl text-center">
            <div className="mb-6">
              <a href="/ai-rehab-insights" className="text-blue-600 dark:text-blue-400 hover:underline text-sm font-medium">
                ← Back to the hub
              </a>
            </div>

            <h1 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900 dark:text-gray-50">
              Success Stories of AI in Rehabilitation
            </h1>

            <p className="text-lg text-gray-700 dark:text-gray-300 max-w-prose mx-auto">
              AI is transforming lives by helping people recover faster and more effectively. Start your journey with our AI-powered injury diagnosis tool to pinpoint your condition and receive personalized guidance. Explore inspiring success stories of individuals who’ve used AI-powered tools to achieve remarkable rehabilitation outcomes.
            </p>
          </div>
        </section>

        {/* Main Content */}
        <section className="py-12">
          <div className="container mx-auto px-6 max-w-3xl prose prose-lg dark:prose-invert space-y-8">
            <h2>Real-World Examples of AI in Rehabilitation</h2>
            <p>
              Here are some real-world examples of how AI has been successfully used to aid rehabilitation:
            </p>
            <ul>
              <li><strong>Knee Injury Recovery:</strong> Ethan used our AI-powered injury diagnosis tool to pinpoint the cause of his long-term knee pain. With personalized exercises, he improved his strength and mobility in just weeks.</li>
              <li><strong>Rehab After Surgery:</strong> Sarah, recovering from ACL surgery, followed a tailored rehab plan generated by AI, regaining strength and flexibility faster than expected.</li>
              <li><strong>Chronic Back Pain Relief:</strong> John started with the injury diagnosis tool to analyze his symptoms. By tracking pain levels and mobility through an AI app, he adjusted his exercises daily and achieved significant improvements.</li>
              <li><strong>Tennis Elbow Treatment:</strong> Lucy avoided long waiting times by using AI to identify her condition with self-tests. She started rehabilitation exercises immediately, easing her discomfort within days.</li>
            </ul>

            <h2>What Makes AI-Powered Rehabilitation So Effective?</h2>
            <p>
              The success of AI in rehabilitation lies in its ability to provide personalized, data-driven care:
            </p>
            <ol>
              <li><strong>Accurate Diagnosis:</strong> AI analyzes symptoms to identify issues with precision.</li>
              <li><strong>Tailored Plans:</strong> Programs are customized to the individual’s injury, goals, and progress.</li>
              <li><strong>Continuous Monitoring:</strong> Real-time feedback ensures that exercises are performed correctly and adjustments are made as needed.</li>
              <li><strong>Motivation and Accountability:</strong> AI tracks progress, keeping users engaged and committed.</li>
            </ol>

            <h2>Share Your Story</h2>
            <p>
              Have you experienced the benefits of AI in rehabilitation? We’d love to hear your story! Sharing your journey can inspire others to explore AI-powered recovery tools and achieve their own success.
            </p>
            <Button className="hero-button-primary mt-4">
              <a href="/contact">Share Your Story</a>
            </Button>

            <h2>Learn More About AI in Physical Rehabilitation</h2>
            <p>
              Want to explore more about how AI is revolutionizing recovery? Check out these related topics:
            </p>
            <ul>
              <li><a href="/ai-rehab-insights/ai-physical-rehabilitation/what-is-ai-physical-rehabilitation">AI in Physical Rehabilitation (Hub Page)</a></li>
              <li><a href="/ai-rehab-insights/ai-physical-rehabilitation/benefits-ai-physical-therapy">Benefits of AI in Physical Therapy</a></li>
              <li><a href="/ai-rehab-insights/ai-physical-rehabilitation/limitations-ai-rehabilitation">Limitations of AI in Rehabilitation</a></li>
            </ul>

            <h2>Transform Your Recovery with AI</h2>
            <p>
              Ready to start your own success story? Begin with our AI-powered injury diagnosis tool to identify your condition and unlock a personalized recovery journey. Discover how AI can help you achieve faster, better outcomes.
            </p>
            <Button className="hero-button-primary mt-4">
              <a href="/injury-diagnosis">Start with the Injury Diagnosis Tool</a>
            </Button>
          </div>
        </section>

        {/* Bottom CTA */}
        <section className="py-12 bg-gray-50 dark:bg-gray-900 text-center">
          <div className="container mx-auto px-6 max-w-5xl">
            <Button variant="secondary" className="mx-auto">
              <a href="/ai-rehab-insights">View all rehab topics</a>
            </Button>
          </div>
        </section>
      </main>
    </div>
  );
};

export default SuccessStoriesAIRehabilitation;