import React from 'react';
import TopicCard from '@/components/TopicCard';
import { Activity, ShieldCheck, Dumbbell, Stethoscope } from 'lucide-react';

const aiPhysicalRehabSubtopics = [
  { id: "community-driven-rehab", title: "How the AI-Rehab Community Ranks Exercises", description: "How real user recommendations shape smarter rehab outcomes." },
  { id: "what-is-ai-physical-rehabilitation", title: "What is AI Physical Rehabilitation", description: "Overview of how AI is transforming physical rehabilitation." },
  { id: "ai-injury-identification", title: "AI Injury Identification", description: "Using AI to identify injuries accurately and efficiently." },
  { id: "personalized-rehab-plans", title: "Personalized Rehab Plans", description: "Tailored rehabilitation programs powered by AI." },
  { id: "benefits-ai-physical-therapy", title: "Benefits of AI Physical Therapy", description: "Explore the benefits of integrating AI into physical therapy." },
  { id: "limitations-ai-rehabilitation", title: "Limitations of AI Rehabilitation", description: "Understand the current limitations of AI in rehab." },
  { id: "success-stories-ai-rehabilitation", title: "Success Stories from AI Rehabilitation", description: "Real-life success stories involving AI-based rehab." },
];

const aiPrehabilitationSubtopics = [
  { id: "what-is-ai-powered-prehabilitation", title: "What is AI Powered Prehabilitation", description: "An introduction to AI in prehabilitation strategies." },
  { id: "how-can-ai-help-prevent-injuries", title: "How Can AI Help Prevent Injuries", description: "How AI assists in preventing injuries before they occur." },
  { id: "prehab-exercises-tailored-by-ai", title: "Prehab Exercises Tailored by AI", description: "Custom exercise routines generated by AI." },
  { id: "is-ai-prehabilitation-effective-for-surgery-prep", title: "Is AI Prehabilitation Effective for Surgery Prep", description: "Evaluate the effectiveness of AI in surgical prep." },
  { id: "how-does-ai-analyze-your-prehab-needs", title: "How Does AI Analyze Your Prehab Needs", description: "Insight into AI's prehabilitation assessment tools." }
];

const aiPersonalTrainingSubtopics = [
  { id: "what-is-ai-powered-personal-training", title: "What is AI Powered Personal Training", description: "Learn about AI's role in personal fitness training." },
  { id: "how-can-ai-help-optimize-training-results", title: "How Can AI Help Optimize Training Results", description: "Using AI to improve training efficiency and outcomes." },
  { id: "examples-of-ai-personalized-workouts", title: "Examples of AI Personalized Workouts", description: "Real-world examples of AI-generated workout routines." },
  { id: "is-ai-effective-for-specific-fitness-goals", title: "Is AI Effective for Specific Fitness Goals", description: "Explore the effectiveness of AI in targeted fitness." },
  { id: "how-does-ai-track-progress-in-training", title: "How Does AI Track Progress in Training", description: "AI tools that monitor and evaluate your progress." }
];

const aiPhysiotherapySubtopics = [
  { id: "how-ai-transforms-physiotherapy", title: "How AI Transforms Physiotherapy", description: "A look into how AI is revolutionizing physiotherapy." },
  { id: "ai-in-injury-identification", title: "AI in Injury Identification", description: "Using AI in the diagnostic phase of physiotherapy." },
  { id: "ai-for-rehabilitation-exercises", title: "AI for Rehabilitation Exercises", description: "Guiding recovery exercises using AI." },
  { id: "ai-in-prehab-and-injury-prevention", title: "AI in Prehab and Injury Prevention", description: "How AI assists in prevention and preparation." },
  { id: "personalized-ai-training-for-recovery-and-fitness", title: "Personalized AI Training for Recovery and Fitness", description: "Tailoring recovery and fitness plans with AI." },
  { id: "online-physiotherapy", title: "Online Physiotherapy", description: "Accessing physiotherapy remotely with AI support." },
  { id: "virtual-vs-traditional-physio", title: "Virtual vs Traditional Physio", description: "Comparing AI-supported and conventional physio approaches." },
  { id: "ai-physiotherapist", title: "AI Physiotherapist", description: "Meet the AI-powered digital physio assistant." },
  { id: "home-physio-guide", title: "Home Physio Guide", description: "How AI supports home-based physiotherapy routines." },
  { id: "the-future-of-ai-in-physiotherapy-and-fitness", title: "The Future of AI in Physiotherapy and Fitness", description: "Exploring the future of AI in physical health." },
  { id: "virtual-physio-faq", title: "Virtual Physio FAQ", description: "Common questions about AI-supported virtual physio." }
];

const TopicGrid = () => {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-fade-in">
      <TopicCard
        id="ai-physical-rehabilitation"
        title="AI Physical Rehabilitation"
        description="Explore how AI is revolutionizing injury recovery and therapy."
        icon={<Activity className="h-6 w-6 text-blue-600" />}
        subtopics={aiPhysicalRehabSubtopics}
        color="bg-gradient-to-br from-white to-blue-50 dark:from-gray-800 dark:to-gray-900"
      />
      <TopicCard
        id="ai-prehabilitation"
        title="AI Prehabilitation"
        description="Prevent injuries with AI-driven assessment and planning."
        icon={<ShieldCheck className="h-6 w-6 text-green-600" />}
        subtopics={aiPrehabilitationSubtopics}
        color="bg-gradient-to-br from-white to-green-50 dark:from-gray-800 dark:to-gray-900"
      />
      <TopicCard
        id="ai-personal-training"
        title="AI Personal Training"
        description="Optimize training results with intelligent guidance."
        icon={<Dumbbell className="h-6 w-6 text-indigo-600" />}
        subtopics={aiPersonalTrainingSubtopics}
        color="bg-gradient-to-br from-white to-indigo-50 dark:from-gray-800 dark:to-gray-900"
      />
      <TopicCard
        id="ai-physiotherapy"
        title="AI Physiotherapy"
        description="Access smarter physiotherapy solutions, anytime."
        icon={<Stethoscope className="h-6 w-6 text-purple-600" />}
        subtopics={aiPhysiotherapySubtopics}
        color="bg-gradient-to-br from-white to-purple-50 dark:from-gray-800 dark:to-gray-900"
      />
    </div>
  );
};

export default TopicGrid;