import React from 'react';

export default function TermsAndConditions() {
  return (
    <>
      <h1>Terms and Conditions</h1>

      <p>Last updated: May 26, 2025</p>

      <p>
        These Terms and Conditions ("Terms") govern your access to and use of AI-Rehab,
        operated by AI-Rehab, located at 96 Spencer Way, United Kingdom.
      </p>

      <p>
        By accessing or using the AI-Rehab website, platform, or any associated services,
        you agree to be bound by these Terms. If you do not agree with any part of these Terms,
        you must not use the service.
      </p>

      <h2>1. About Our Services</h2>
      <p>
        AI-Rehab provides AI-powered tools for physical rehabilitation, prehabilitation, and personal training.
        The service generates exercise recommendations based on user inputs but does not constitute professional medical advice.
      </p>

      <h2>2. Medical Disclaimer</h2>
      <p>
        The content and suggestions generated by AI-Rehab are for informational purposes only
        and are not intended as a substitute for professional medical advice, diagnosis, or treatment.
        Always consult a qualified health provider with any questions you may have regarding a medical condition.
      </p>

      <p>
        Use of the platform is at your own risk. AI-Rehab is not responsible for any injury, harm,
        or damage resulting from the use of its services.
      </p>

      <h2>3. User Accounts</h2>
      <p>
        To use core features of AI-Rehab, users must register and log in. You are responsible for maintaining the confidentiality of your login credentials.
        You agree not to share your account with others or allow unauthorized access.
      </p>

      <p>
        We reserve the right to suspend or terminate your account at any time if you breach these Terms
        or if we detect suspicious or abusive behavior.
      </p>

      <h2>4. Future Subscriptions and Paid Features</h2>
      <p>
        While AI-Rehab is currently free to use, we may introduce paid subscription tiers or premium features in the future.
        If so, users will be notified and required to agree to separate billing terms and conditions.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>By using the service, you agree not to:</p>
      <ul>
        <li>Use the platform for any unlawful purpose</li>
        <li>Share, distribute, scrape, or republish generated content</li>
        <li>Copy or reverse-engineer our technology or designs</li>
        <li>Upload or input false, misleading, or malicious information</li>
        <li>Violate intellectual property rights of AI-Rehab or others</li>
      </ul>

      <h2>6. Intellectual Property</h2>
      <p>
        All content on the platform, including software, text, graphics, and branding, is the intellectual property of AI-Rehab unless stated otherwise.
        You may not reproduce, distribute, or use it without explicit written permission.
      </p>

      <h2>7. Availability and Changes</h2>
      <p>
        We do not guarantee that the platform will always be available or uninterrupted. 
        We reserve the right to modify or discontinue any part of the service at any time, without notice.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, AI-Rehab shall not be liable for any indirect, incidental, 
        special, or consequential damages, including personal injury, arising from the use of the service.
      </p>

      <h2>9. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless AI-Rehab, its affiliates, directors, and employees from any claims, damages, liabilities,
        and expenses arising out of your use of the service, your violation of these Terms, or your violation of any rights of a third party.
      </p>

      <h2>10. Governing Law</h2>
      <p>
        These Terms are governed by and construed in accordance with the laws of England and Wales.
        Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts of the United Kingdom.
      </p>

      <h2>11. Changes to These Terms</h2>
      <p>
        We may update these Terms at any time. Changes will be posted on this page with an updated “last modified” date.
        Continued use of the service after changes are made constitutes your acceptance of the new Terms.
      </p>

      <h2>12. Contact</h2>
      <p>
        If you have any questions or concerns about these Terms, please contact us at hello@ai-rehab.co.uk.
      </p>
    </>
  );
}
