import { describe, it, expect, vi, beforeEach } from 'vitest'
import { NextRequest } from 'next/server'
import { POST } from '../route'

// Mock OpenAI
vi.mock('openai', () => ({
  default: vi.fn().mockImplementation(() => ({
    responses: {
      create: vi.fn().mockResolvedValue({
        output_text: JSON.stringify({
          summary: 'This is a test business summary generated by AI.',
          products: [
            {
              name: 'Test Product',
              description: 'A test product description',
              price: 25
            }
          ]
        })
      }),
    },
  })),
}))

describe('POST /api/ai/generate-business-summary', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('generates business summary successfully', async () => {
    const requestBody = {
      businessName: 'Test Business',
      paragraph: 'A test business description paragraph',
    }

    const request = new NextRequest('http://localhost:3000/api/ai/generate-business-summary', {
      method: 'POST',
      body: JSON.stringify(requestBody),
    })

    const response = await POST(request)
    const data = await response.json()

    expect(response.status).toBe(200)
    expect(data).toHaveProperty('data')
    expect(data.data).toHaveProperty('summary')
    expect(data.data).toHaveProperty('products')
  })

  it('returns error for invalid request body', async () => {
    const request = new NextRequest('http://localhost:3000/api/ai/generate-business-summary', {
      method: 'POST',
      body: 'invalid json',
    })

    const response = await POST(request)
    
    // Now the route properly handles invalid JSON and returns 400
    expect(response.status).toBe(400)
    const data = await response.json()
    expect(data).toHaveProperty('error')
  })

  it('returns error for missing required fields', async () => {
    const requestBody = {
      businessName: 'Test Business',
      // Missing paragraph field
    }

    const request = new NextRequest('http://localhost:3000/api/ai/generate-business-summary', {
      method: 'POST',
      body: JSON.stringify(requestBody),
    })

    const response = await POST(request)
    
    // Now the route properly validates required fields and returns 400
    expect(response.status).toBe(400)
    const data = await response.json()
    expect(data).toHaveProperty('error')
  })
})
