import { http, HttpResponse } from 'msw'

// Mock Supabase auth responses
export const handlers = [
  // Mock Supabase auth endpoints
  http.post('*/auth/v1/token', () => {
    return HttpResponse.json({
      access_token: 'mock-access-token',
      refresh_token: 'mock-refresh-token',
      expires_in: 3600,
      token_type: 'bearer',
    })
  }),

  // Mock business endpoints
  http.get('*/rest/v1/businesses', () => {
    return HttpResponse.json([
      {
        id: '1',
        name: 'Test Business',
        slug: 'test-business',
        description: 'A test business',
        created_at: '2024-01-01T00:00:00Z',
      },
    ])
  }),

  // Mock Stripe endpoints
  http.post('*/v1/checkout/sessions', () => {
    return HttpResponse.json({
      id: 'cs_test_123',
      url: 'https://checkout.stripe.com/test',
    })
  }),

  // Mock email endpoints
  http.post('*/api/email/send', () => {
    return HttpResponse.json({ success: true })
  }),

  // Mock messaging endpoints
  http.get('*/api/messaging/conversations', () => {
    return HttpResponse.json([])
  }),

  // Mock AI endpoints
  http.post('*/api/ai/generate-business-summary', () => {
    return HttpResponse.json({
      summary: 'This is a test business summary generated by AI.',
    })
  }),

  // Default handler for unmatched requests
  http.all('*', ({ request }) => {
    console.warn(`Unhandled ${request.method} request to ${request.url}`)
    return HttpResponse.json({ error: 'Not found' }, { status: 404 })
  }),
]

